### ISSUE TITLE
Null output commands

### ISSUE THREAD

**Issue by stevepeak** [asyncy/hub#32]
If a command has `null` output then the `results = ` should be removed from the syntax example.

### Example with null output

```yaml
commands:
  foobar:
    arguments: 
      ..
    output: null
```
    
OR
    
```yaml
commands:
  foobar:
    arguments: 
      ..
    output:
      type: null
```
